from __future__ import annotations
import warnings
import torch
from typing import Optional, Dict, Any, List
from torch_geometric.loader import DataLoader
from collections import defaultdict

from scipy.stats import wasserstein_distance
from tqdm import tqdm
from graph_signal_diffusion.baselines import BASELINE_REGISTRY
from graph_signal_diffusion.baselines.base import BaseBaseline
from graph_signal_diffusion.baselines.plot_utils import ecdf as _ecdf
from graph_signal_diffusion.evaluation import structural_metrics as sm


@BASELINE_REGISTRY.register("grw")
class GeometricRandomWalk(BaseBaseline):
    """
    Static Geometric Random Walk baseline for stock price forecasting.

    Fits per-stock i.i.d. Gaussian log-return parameters once on the training
    set using empirical Bayes shrinkage, then generates unconditional samples
    at test time (ignoring the historical window).

    The baseline operates entirely in **standardized** space (z-scored log
    returns with std ≈ 1).  TaskV2's destandardisation pipeline converts both
    generated and real samples back to raw log returns and prices for metric
    computation.

    Attributes:
        has_ensemble_evaluate: Signals to ``UnifiedEvaluator`` that this
            baseline handles its own multi-sample evaluation via ``evaluate()``.
    """

    # Let the evaluator know we handle ensemble evaluation ourselves.
    has_ensemble_evaluate: bool = True

    def __init__(
        self,
        device: str = "cuda",
        n_samples: int = 20,
        shrinkage_strength: float = 10.0,
        min_samples_per_stock: int = 20,
        evaluation: Optional[Dict[str, Any]] = None,
        **kwargs,
    ):
        """
        Args:
            device: Device to run computations on.
            n_samples: Number of Monte-Carlo samples per input for ensemble
                evaluation.
            shrinkage_strength: Bayesian shrinkage hyper-parameter *k*.
                Effective shrinkage weight per stock is λ = n_s / (n_s + k).
            min_samples_per_stock: Minimum observations required to estimate
                per-stock parameters; stocks with fewer observations fall back
                to global estimates.
            evaluation: Nested dict of evaluation-time settings.  When
                instantiated via Hydra the ``evaluation:`` YAML sub-tree is
                automatically passed as a dict.  Recognised keys:

                - *structural_metrics* (``bool``, default ``False``): compute
                  autocorrelation-of-r² and eigenvalue-spectrum diagnostics.
                - *structural_max_lag* (``int``, default ``2``): max lag for
                  the autocorrelation profile.
                - *structural_n_eigenvalues* (``int``, default ``5``): number
                  of top eigenvalues to compute.
                - *nll_metrics* (``bool``, default ``False``): compute
                  per-trajectory NLL under the fitted GRW and Wasserstein-1.
                - *log_every_n_batches* (``int``, default ``10``): progress
                  print frequency (``0`` to disable).
        """
        super().__init__(device=torch.device(device), **kwargs)
        self.n_samples = n_samples
        self.shrinkage_strength = shrinkage_strength
        self.min_samples_per_stock = min_samples_per_stock

        # Evaluation settings (from nested YAML block or defaults)
        eval_cfg = dict(evaluation) if evaluation else {}
        self.structural_metrics: bool = eval_cfg.get("structural_metrics", False)
        self.structural_max_lag: int = eval_cfg.get("structural_max_lag", 2)
        self.structural_n_eigenvalues: int = eval_cfg.get("structural_n_eigenvalues", 5)
        self.nll_metrics: bool = eval_cfg.get("nll_metrics", False)
        self.log_every_n_batches: int = eval_cfg.get("log_every_n_batches", 10)
        self.plot_bins: int = eval_cfg.get("plot_bins", 60)
        self.plot_dpi: int = eval_cfg.get("plot_dpi", 150)
        self.plot_nll_log_x: bool = bool(eval_cfg.get("plot_nll_log_x", True))
        # When True, save raw plot-data sidecars (.npz) next to every
        # polished PDF so that figures can be regenerated by
        # ``python -m graph_signal_diffusion.cli.replot_baselines`` without
        # re-running evaluation.
        self.dump_plot_data: bool = bool(eval_cfg.get("dump_plot_data", True))

        # Fitted parameters (populated by fit())
        self.global_mean: Optional[float] = None
        self.global_std: Optional[float] = None
        self.per_stock_means: Dict[int, float] = {}
        self.per_stock_stds: Dict[int, float] = {}
        self.n_stocks: int = 0

    # ------------------------------------------------------------------
    # Fitting
    # ------------------------------------------------------------------

    def fit(
        self,
        train_loader: DataLoader,
        val_loader: Optional[DataLoader] = None,
        **kwargs,
    ):
        """Estimate per-stock (μ_s, σ_s) with empirical Bayes shrinkage.

        Steps:
            1. Collect all z-scored log returns from ``batch.y`` per stock.
            2. Compute global statistics (μ_global, σ_global).
            3. Per stock with ≥ ``min_samples_per_stock`` observations,
               compute MLE (μ_s, σ_s) and shrink toward the global:
               ``λ = n_s / (n_s + k)``; ``μ̃_s = λ·μ_s + (1−λ)·μ_global``.
            4. Stocks with too few observations use global parameters.
        """
        print("\nFitting GRW baseline with shrinkage...")

        returns_by_stock: Dict[int, List[torch.Tensor]] = defaultdict(list)
        all_returns: List[torch.Tensor] = []

        for batch in train_loader:
            batch = batch.to("cpu")  # collect on CPU to avoid GPU OOM
            log_returns = batch.y.squeeze(-1)  # [B*N, T]
            B = batch.num_graphs
            N = log_returns.size(0) // B
            log_returns = log_returns.view(B, N, -1)  # [B, N, T]

            for s in range(N):
                stock_ret = log_returns[:, s, :].reshape(-1)  # [B*T]
                returns_by_stock[s].append(stock_ret)
                all_returns.append(stock_ret)

        # Global statistics
        all_returns_t = torch.cat(all_returns)
        self.global_mean = all_returns_t.mean().item()
        self.global_std = all_returns_t.std().item()

        # Sanity-check: in standardised space std should be ≈ 1
        if abs(self.global_std - 1.0) > 0.5:
            warnings.warn(
                f"GRW fit: global std = {self.global_std:.4f} (expected ≈ 1.0 "
                f"for standardised data). Check that the dataset applies "
                f"per-stock z-scoring before training."
            )

        print(f"Global parameters: μ={self.global_mean:.6f}, σ={self.global_std:.6f}")

        # Per-stock parameters with shrinkage
        self.n_stocks = len(returns_by_stock)
        print(f"Computing per-stock parameters for {self.n_stocks} stocks...")

        for s in range(self.n_stocks):
            stock_ret = torch.cat(returns_by_stock[s])
            n_obs = len(stock_ret)

            if n_obs >= self.min_samples_per_stock:
                mu_s = stock_ret.mean().item()
                sigma_s = stock_ret.std().item()
                lam = n_obs / (n_obs + self.shrinkage_strength)
                self.per_stock_means[s] = lam * mu_s + (1 - lam) * self.global_mean
                self.per_stock_stds[s] = lam * sigma_s + (1 - lam) * self.global_std
            else:
                self.per_stock_means[s] = self.global_mean
                self.per_stock_stds[s] = self.global_std

        print(f"Fitted {len(self.per_stock_means)} stocks")
        print(
            f"Mean range: [{min(self.per_stock_means.values()):.6f}, "
            f"{max(self.per_stock_means.values()):.6f}]"
        )
        print(
            f"Std range:  [{min(self.per_stock_stds.values()):.6f}, "
            f"{max(self.per_stock_stds.values()):.6f}]"
        )

    # ------------------------------------------------------------------
    # Vectorised sampling helper
    # ------------------------------------------------------------------

    def _sample_returns(self, B: int, T: int, N: int) -> torch.Tensor:
        """Sample i.i.d. z-scored returns for all stocks (vectorised).

        Returns:
            Tensor of shape ``[B, T, N, 1]`` on ``self.device``.
        """
        # Build per-stock parameter tensors [N]
        mu = torch.tensor(
            [self.per_stock_means.get(s, self.global_mean) for s in range(N)],
            device=self.device,
        )
        sigma = torch.tensor(
            [self.per_stock_stds.get(s, self.global_std) for s in range(N)],
            device=self.device,
        )

        # Sample: [B, T, N] ~ N(0,1), then scale
        z = torch.randn(B, T, N, device=self.device)
        returns = z * sigma.unsqueeze(0).unsqueeze(0) + mu.unsqueeze(0).unsqueeze(0)
        return returns.unsqueeze(-1)  # [B, T, N, 1]

    # ------------------------------------------------------------------
    # Analytical likelihood
    # ------------------------------------------------------------------

    def compute_nll(self, returns: torch.Tensor) -> torch.Tensor:
        """Compute per-trajectory NLL under the fitted GRW model.

        Each trajectory's NLL is the **sum** (not mean) of per-step,
        per-stock negative log-likelihoods.  No averaging over time,
        stocks, or batch is applied.  The resulting vector has one entry
        per graph and is the natural unit for NLL histogram comparisons.

        Concretely, for batch element *b*:

        .. math::

            \\text{NLL}_b = -\\sum_{s=1}^{N}\\sum_{t=1}^{T}
            \\log \\mathcal{N}(r_{b,t,s} \\mid \\tilde{\\mu}_s, \\tilde{\\sigma}_s^2)

        Args:
            returns: Standardised log-returns in shape ``[B, T, N]`` or
                ``[B, T, N, 1]`` — the same space as ``batch.y``
                (z-scored log returns, std ≈ 1).

        Returns:
            1-D tensor of shape ``[B]`` containing the per-trajectory NLL
            summed over all *T* timesteps and *N* stocks.
        """
        import math

        if returns.dim() == 4:
            returns = returns.squeeze(-1)  # [B, T, N]
        B, T, N = returns.shape

        mu = torch.tensor(
            [self.per_stock_means.get(s, self.global_mean) for s in range(N)],
            dtype=returns.dtype,
            device=returns.device,
        )  # [N]
        sigma = torch.tensor(
            [self.per_stock_stds.get(s, self.global_std) for s in range(N)],
            dtype=returns.dtype,
            device=returns.device,
        )  # [N]

        # log p(r | μ, σ) = -½ log(2π) - log σ - (r−μ)² / (2σ²)
        log_probs = (
            -0.5 * math.log(2.0 * math.pi)
            - sigma.log()                                            # [N]
            - 0.5 * ((returns - mu) / sigma) ** 2                   # [B, T, N]
        )  # broadcast: result is [B, T, N]

        # Sum over T and N (no averaging) → [B]
        return -log_probs.sum(dim=(1, 2))

    def compute_cumulative_nll(
        self,
        returns: torch.Tensor,
    ) -> torch.Tensor:
        """NLL of *cumulative* log-returns at each horizon under the GRW model.

        For each prediction horizon :math:`t` the cumulative log-return is
        :math:`R_{b,t,s} = \\sum_{\\tau=1}^{t} r_{b,\\tau,s}` and, under GRW
        (i.i.d. steps), the marginal is
        :math:`R_{b,t,s} \\sim \\mathcal{N}(t\\mu_s, t\\sigma_s^2)`.  The NLL
        summed over stocks is therefore:

        .. math::

            \\ell_{b,t} = -\\sum_{s=1}^{N}
            \\log \\mathcal{N}\\!\\left(R_{b,t,s}
            \\,\\middle|\\, t\\mu_s,\\, t\\sigma_s^2\\right)

        Because the GRW distribution at horizon :math:`t` is wider
        than at :math:`t-1`, :math:`\\ell_{b,t}` is NOT stationary:
        if real returns deviate from i.i.d. Gaussian (e.g. via
        autocorrelation or volatility clustering), the gap between the
        real and GRW-generated NLL distributions grows with :math:`t`.

        Args:
            returns: ``[B, T, N]`` or ``[B, T, N, 1]`` standardised
                log-returns.

        Returns:
            ``[B, T]`` tensor: per-trajectory per-horizon cumulative NLL.
        """
        import math

        if returns.dim() == 4:
            returns = returns.squeeze(-1)  # [B, T, N]
        B, T, N = returns.shape

        cum = returns.cumsum(dim=1)  # [B, T, N]  R_{b,t,s}

        mu = torch.tensor(
            [self.per_stock_means.get(s, self.global_mean) for s in range(N)],
            dtype=returns.dtype,
            device=returns.device,
        )  # [N]
        sigma = torch.tensor(
            [self.per_stock_stds.get(s, self.global_std) for s in range(N)],
            dtype=returns.dtype,
            device=returns.device,
        )  # [N]

        # t-step mean and std: [T] broadcast to [1, T, 1]
        t_vec = torch.arange(1, T + 1, dtype=returns.dtype, device=returns.device)
        mu_t    = mu.unsqueeze(0).unsqueeze(0)    * t_vec.view(1, T, 1)   # [1, T, N]
        sigma_t = sigma.unsqueeze(0).unsqueeze(0) * t_vec.view(1, T, 1).sqrt()  # [1, T, N]

        log_probs = (
            -0.5 * math.log(2.0 * math.pi)
            - sigma_t.log()
            - 0.5 * ((cum - mu_t) / sigma_t) ** 2
        )  # [B, T, N]

        return -log_probs.sum(dim=2)  # [B, T]

    # ------------------------------------------------------------------
    # Structural diagnostics
    # ------------------------------------------------------------------

    @staticmethod
    def compute_autocorr_profile(
        returns: torch.Tensor,
        max_lag: int = 10,
    ) -> torch.Tensor:
        """Lag-0…max_lag autocorrelation (standard ACF) of r², averaged over stocks.

        For each lag ``l`` and stock ``s``:

        .. math::

            \\rho_l^{(s)} = \\gamma_l^{(s)} / \\gamma_0^{(s)}

        where :math:`\\gamma_l` uses a single global mean and
        :math:`\\gamma_0 = \\mathrm{Var}(r^2)`.

        Args:
            returns: ``[B, T, N]`` standardised log-returns.
            max_lag: Maximum lag to compute (inclusive).

        Returns:
            ``[max_lag + 1]`` tensor of autocorrelations at lags 0…max_lag.
        """
        B, T, N = returns.shape
        r2 = returns ** 2
        r2_flat = r2.reshape(-1, N)
        mu = r2_flat.mean(0)                      # [N] global mean
        gamma_0 = ((r2_flat - mu) ** 2).mean(0)   # [N] lag-0 autocovariance

        profile = torch.zeros(max_lag + 1)
        profile[0] = 1.0  # ρ(0) = 1
        for lag in range(1, max_lag + 1):
            r2_t = r2[:, :T - lag, :].reshape(-1, N)
            r2_tl = r2[:, lag:, :].reshape(-1, N)

            gamma_l = ((r2_t - mu) * (r2_tl - mu)).mean(0)  # [N]
            rho_l = gamma_l / (gamma_0 + 1e-8)               # [N]
            profile[lag] = rho_l.mean()

        return profile

    @staticmethod
    def compute_autocorr_profile_per_stock(
        returns: torch.Tensor,
        max_lag: int = 10,
    ) -> torch.Tensor:
        """Per-stock lag-0…max_lag autocorrelation (standard ACF) of r².

        Identical to :meth:`compute_autocorr_profile` but retains the
        per-stock dimension instead of averaging over stocks.

        Args:
            returns: ``[B, T, N]`` standardised log-returns.
            max_lag: Maximum lag to compute (inclusive).

        Returns:
            ``[max_lag + 1, N]`` tensor — row *l* holds the ACF at
            lag *l* for every individual stock.  Row 0 is identically 1.
        """
        B, T, N = returns.shape
        r2 = returns ** 2
        r2_flat = r2.reshape(-1, N)
        mu = r2_flat.mean(0)                      # [N] global mean
        gamma_0 = ((r2_flat - mu) ** 2).mean(0)   # [N] lag-0 autocovariance

        profile = torch.zeros(max_lag + 1, N)
        profile[0] = 1.0  # ρ(0) = 1 for every stock
        for lag in range(1, max_lag + 1):
            r2_t  = r2[:, :T - lag, :].reshape(-1, N)
            r2_tl = r2[:, lag:, :].reshape(-1, N)

            gamma_l = ((r2_t - mu) * (r2_tl - mu)).mean(0)  # [N]
            profile[lag] = gamma_l / (gamma_0 + 1e-8)

        return profile  # [max_lag + 1, N]

    @staticmethod
    def compute_top_eigenvalues(
        returns: torch.Tensor, k: int = 5
    ) -> torch.Tensor:
        """Top-k eigenvalues of the empirical return correlation matrix.

        Observations are pooled over *B* batches and *T* timesteps, giving
        an ``[B*T, N]`` design matrix.  Under i.i.d. independent stocks
        (GRW) all eigenvalues are ≈ 1; under a factor model the first
        eigenvalue is ≫ 1.

        Args:
            returns: ``[B, T, N]`` standardised log-returns.
            k: Number of top eigenvalues to return.

        Returns:
            Eigenvalues in descending order, shape ``[k]``.
        """
        B, T, N = returns.shape
        r = returns.reshape(-1, N).float()

        r = r - r.mean(0)
        r = r / (r.std(0) + 1e-8)

        C = (r.T @ r) / r.shape[0]
        vals = torch.linalg.eigvalsh(C)
        return vals.flip(0)[:k]

    compute_structural_metrics = staticmethod(sm.compute_structural_metrics)

    # ------------------------------------------------------------------
    # Visualisation helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _plot_nll_histograms(
        nll_real: Any,
        nll_gen: Any,
        save_path: str,
        bins: int = 60,
        dpi: int = 150,
        log_x: bool = True,
    ) -> None:
        """Save a two-panel NLL histogram + empirical-CDF figure.

        Left panel: overlaid density histograms of per-trajectory NLL for
        real and GRW-generated returns.
        Right panel: empirical CDFs with |ΔCDF| area shaded (W₁ integrand).

        Args:
            nll_real: 1-D numpy array of NLL values for real returns.
            nll_gen:  1-D numpy array of NLL values for generated returns.
            save_path: File path to save the PNG.
            bins: Number of histogram bins.
            dpi: Figure DPI.
        """
        import os
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import numpy as np
        from scipy.stats import wasserstein_distance as _w1

        w1 = float(_w1(nll_real, nll_gen))

        # Build empirical CDFs
        all_vals = np.concatenate([nll_real, nll_gen])
        x_min, x_max = float(all_vals.min()), float(all_vals.max())
        if log_x and x_min > 0:
            x_grid = np.logspace(np.log10(x_min), np.log10(x_max), 2000)
            hist_bins = np.logspace(np.log10(x_min), np.log10(x_max), bins + 1)
        else:
            x_grid = np.linspace(x_min, x_max, 2000)
            hist_bins = bins

        cdf_real = _ecdf(nll_real, x_grid)
        cdf_gen = _ecdf(nll_gen, x_grid)

        fig, (ax_hist, ax_cdf) = plt.subplots(
            1, 2, figsize=(14, 5),
            gridspec_kw={"width_ratios": [1.2, 1]},
        )

        # Left — density histograms
        ax_hist.hist(
            nll_real, bins=hist_bins, density=True, alpha=0.55, color="steelblue",
            label=(
                r"$\mathrm{NLL}_{\mathrm{GRW}}(r^{\mathrm{real}})$  "
                f"  \u03bc={nll_real.mean():.1f},  \u03c3={nll_real.std():.1f}"
            ),
        )
        ax_hist.hist(
            nll_gen, bins=hist_bins, density=True, alpha=0.50, color="tab:orange",
            label=(
                r"$\mathrm{NLL}_{\mathrm{GRW}}(r^{\mathrm{gen}})$  "
                f"  \u03bc={nll_gen.mean():.1f},  \u03c3={nll_gen.std():.1f}"
            ),
        )
        if log_x and x_min > 0:
            ax_hist.set_xscale("log")
        ax_hist.set_xlabel(
            r"Per-trajectory NLL  $= \sum_{s,t} -\log\,\mathcal{N}"
            r"(r_{s,t}\mid\tilde{\mu}_s,\tilde{\sigma}_s^2)$",
            fontsize=11,
        )
        ax_hist.set_ylabel("Density", fontsize=11)
        ax_hist.set_title("NLL Histograms  (real vs GRW-generated)", fontsize=12)
        ax_hist.legend(fontsize=9)

        # Right — empirical CDFs
        ax_cdf.plot(x_grid, cdf_real, color="steelblue", linewidth=1.8,
                    label=r"$F_{\mathrm{real}}$")
        ax_cdf.plot(x_grid, cdf_gen, color="tab:orange", linewidth=1.8,
                    label=r"$F_{\mathrm{gen}}$")
        ax_cdf.fill_between(
            x_grid, cdf_real, cdf_gen, alpha=0.25, color="mediumpurple",
            label=fr"$|F_{{\rm real}} - F_{{\rm gen}}|$  (area = W$_1$ = {w1:.2f})",
        )
        if log_x and x_min > 0:
            ax_cdf.set_xscale("log")
        ax_cdf.set_xlabel(r"Per-trajectory NLL  $\ell$", fontsize=11)
        ax_cdf.set_ylabel("Empirical CDF", fontsize=11)
        ax_cdf.set_title(
            f"Empirical CDFs \u2014 $W_1 = {w1:.2f}$ nats", fontsize=12,
        )
        ax_cdf.legend(fontsize=9)
        ax_cdf.set_ylim(0, 1)

        # fig.tight_layout()
        os.makedirs(os.path.dirname(save_path) or ".", exist_ok=True)
        fig.savefig(save_path, dpi=dpi)
        plt.close(fig)
        print(f"  [GRW] NLL histogram saved to: {save_path}")

    @staticmethod
    def _plot_cumulative_nll_histograms(
        nll_real_bt: Any,
        nll_gen_bt: Any,
        save_path: str,
        bins: int = 60,
        dpi: int = 150,
    ) -> None:
        """Plot cumulative-return NLL histograms + CDFs for each horizon.

        Produces a 2-row grid with *T* columns (one per prediction horizon):

        * **Top row** — overlaid density histograms of
          :math:`\\ell_{b,t}^{\\text{real}}` and
          :math:`\\ell_{b,t}^{\\text{gen}}` under the :math:`t`-step GRW
          model, including their means.
        * **Bottom row** — empirical CDFs of both distributions with the
          :math:`|\\Delta F|` area shaded and the Wasserstein-1 distance
          annotated.

        Args:
            nll_real_bt: ``[B, T]`` numpy array — cumulative NLL (real).
            nll_gen_bt:  ``[B, T]`` numpy array — cumulative NLL (generated).
            save_path:   Destination file path.
            bins:        Histogram bins per panel.
            dpi:         Figure DPI.
        """
        import os
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import numpy as np
        from scipy.stats import wasserstein_distance as _w1

        B, T = nll_real_bt.shape

        fig, axes = plt.subplots(
            2, T,
            figsize=(7 * T, 10),
            gridspec_kw={"hspace": 0.40, "wspace": 0.28},
        )
        # Ensure axes is always 2-D
        if T == 1:
            axes = axes.reshape(2, 1)

        w1_values = []
        for t in range(T):
            real_t = nll_real_bt[:, t]
            gen_t  = nll_gen_bt[:, t]
            w1     = float(_w1(real_t, gen_t))
            w1_values.append(w1)

            # ---- top: histograms ----------------------------------------
            ax_h = axes[0, t]
            all_t = np.concatenate([real_t, gen_t])
            lo, hi = np.percentile(all_t, 0.5), np.percentile(all_t, 99.5)
            bin_edges = np.linspace(lo, hi, bins + 1)

            ax_h.hist(real_t, bins=bin_edges, density=True,
                      alpha=0.55, color="steelblue",
                      label=(
                          r"real  $\mu$=" + f"{real_t.mean():.1f}"
                          + r",  $\sigma$=" + f"{real_t.std():.1f}"
                      ))
            ax_h.hist(gen_t, bins=bin_edges, density=True,
                      alpha=0.50, color="tab:orange",
                      label=(
                          r"gen  $\mu$=" + f"{gen_t.mean():.1f}"
                          + r",  $\sigma$=" + f"{gen_t.std():.1f}"
                      ))
            ax_h.set_title(f"$t = {t+1}$", fontsize=14)
            ax_h.set_xlabel(
                r"Cumulative NLL  $\ell_{b," + str(t+1) + r"}$",
                fontsize=11,
            )
            if t == 0:
                ax_h.set_ylabel("Density", fontsize=11)
            ax_h.legend(fontsize=9)

            # ---- bottom: CDFs -------------------------------------------
            ax_c = axes[1, t]
            x_lo = min(real_t.min(), gen_t.min())
            x_hi = max(real_t.max(), gen_t.max())
            x_grid = np.linspace(x_lo, x_hi, 2000)
            cdf_real = _ecdf(real_t, x_grid)
            cdf_gen  = _ecdf(gen_t,  x_grid)

            ax_c.plot(x_grid, cdf_real, color="steelblue",    linewidth=1.8,
                      label=r"$F_{\mathrm{real}}$")
            ax_c.plot(x_grid, cdf_gen,  color="tab:orange", linewidth=1.8,
                      label=r"$F_{\mathrm{gen}}$")
            ax_c.fill_between(
                x_grid, cdf_real, cdf_gen,
                alpha=0.22, color="mediumpurple",
                label=fr"$W_1={w1:.2f}$",
            )
            ax_c.set_xlabel(
                r"Cumulative NLL  $\ell_{b," + str(t+1) + r"}$",
                fontsize=11,
            )
            if t == 0:
                ax_c.set_ylabel("Empirical CDF", fontsize=11)
            ax_c.set_ylim(0, 1)
            ax_c.legend(fontsize=9)

        # Super-titles
        fig.suptitle(
            r"NLL of cumulative log-returns under $t$-step GRW model"
            "\n"
            r"$\ell_{b,t}=-\sum_s\log\mathcal{N}(R_{b,t,s}\mid t\mu_s,\,"
            r"t\sigma_s^2)$",
            fontsize=12, y=1.01,
        )

        os.makedirs(os.path.dirname(save_path) or ".", exist_ok=True)
        fig.savefig(save_path, dpi=dpi, bbox_inches="tight")
        plt.close(fig)
        print(f"  [GRW] Cumulative NLL histogram saved to: {save_path}")
        return w1_values

    @staticmethod
    def _plot_structural_metrics(
        real_returns, gen_returns, save_path, max_lag=2,
        n_eigenvalues=5, dpi=150, model_name="GRW",
        window_stride=1, window_start_indices=None,
    ):
        """Delegate to shared :func:`sm.plot_structural_metrics`.

        Args:
            window_start_indices: ``[B]`` integer tensor of window start
                positions passed to the phased estimator for order-robust
                phase assignment.  ``None`` falls back to positional slicing.
        """
        sm.plot_structural_metrics(
            real_returns, gen_returns, save_path,
            max_lag=max_lag, n_eigenvalues=n_eigenvalues,
            dpi=dpi, model_name=model_name,
            window_stride=window_stride,
            window_start_indices=window_start_indices,
        )

    @staticmethod
    def _plot_autocorr_per_stock(
        real_returns, gen_returns, save_path, max_lag=2,
        dpi=150, model_name="GRW",
        window_stride=1, window_start_indices=None,
    ):
        """Delegate to shared :func:`sm.plot_autocorr_per_stock`.

        Args:
            window_start_indices: ``[B]`` integer tensor of window start
                positions for order-robust phase assignment.
        """
        sm.plot_autocorr_per_stock(
            real_returns, gen_returns, save_path,
            max_lag=max_lag, dpi=dpi, model_name=model_name,
            window_stride=window_stride,
            window_start_indices=window_start_indices,
        )

    # ------------------------------------------------------------------
    # Cumulative return diagnostics
    # ------------------------------------------------------------------

    compute_cumulative_return_std = staticmethod(sm.compute_cumulative_return_std)

    @staticmethod
    def _plot_cumulative_return_std(
        std_real, std_gen, save_path, theoretical=None,
        std_real_tn=None, std_gen_tn=None, dpi=150, model_name="GRW",
    ):
        """Delegate to shared :func:`sm.plot_cumulative_return_std`."""
        sm.plot_cumulative_return_std(
            std_real, std_gen, save_path,
            theoretical=theoretical,
            std_real_tn=std_real_tn, std_gen_tn=std_gen_tn,
            dpi=dpi, model_name=model_name,
        )

    # ------------------------------------------------------------------
    # Prediction (single-sample, for UnifiedEvaluator's generic path)
    # ------------------------------------------------------------------

    def predict(self, data) -> torch.Tensor:
        """Return *point* predictions (ensemble mean) as ``[B, T, N, 1]``.

        This is used by ``UnifiedEvaluator.evaluate_baseline`` for baselines
        that don't declare ``has_ensemble_evaluate``.  For GRW the ensemble
        mean is just ``(μ_s)`` repeated, since each draw is i.i.d.
        """
        B = data.num_graphs
        N = data.y.size(0) // B
        T = data.y.size(1)

        # Analytical mean — no need to actually sample
        mu = torch.tensor(
            [self.per_stock_means.get(s, self.global_mean) for s in range(N)],
            device=self.device,
        )
        # Broadcast to [B, T, N, 1]
        return mu.view(1, 1, N, 1).expand(B, T, -1, -1).clone()

    # ------------------------------------------------------------------
    # Ensemble prediction (multi-sample)
    # ------------------------------------------------------------------

    def predict_ensemble(self, data) -> torch.Tensor:
        """Generate ``n_samples`` i.i.d. return paths per input.

        Returns:
            ``[B * n_samples, T, N, 1]`` with samples for the same input
            contiguous (positions ``[b*n .. (b+1)*n - 1]``).
        """
        B = data.num_graphs
        N = data.y.size(0) // B
        T = data.y.size(1)

        samples = []
        for _ in range(self.n_samples):
            samples.append(self._sample_returns(B, T, N))

        # Stack → [B, n, T, N, 1], then interleave to [B*n, T, N, 1]
        stacked = torch.stack(samples, dim=1)  # [B, n, T, N, 1]
        return stacked.reshape(B * self.n_samples, T, N, 1)

    # ------------------------------------------------------------------
    # Evaluation (full V2-compatible pipeline)
    # ------------------------------------------------------------------

    def evaluate(
        self,
        loader: DataLoader,
        task,
        max_batches: Optional[int] = None,
        viz_save_dir: Optional[str] = None,
        eval_split_name: str = "eval",
    ) -> Dict[str, float]:
        """Evaluate with the TaskV2 probabilistic pipeline (per-batch).

        Follows the same pattern as ``DiffusionTrainer.evaluate_v2``:
        evaluate each batch independently via ``task.evaluate_samples()``,
        accumulate the scalar metrics, and average at the end.  This avoids
        concatenating all predictions/targets into a single tensor which
        would cause GPU OOM on large datasets.

        For each batch:
        1. ``task.prepare_data(data)`` → targets ``[B, T, N, F]`` + metadata.
        2. ``predict_ensemble(data)`` → ``[B*n, T, N, F]``.
        3. Replicate targets & metadata tensors ``n`` times to match.
        4. Call ``task.evaluate_samples()`` **per batch** to get metrics.
        5. Accumulate metrics across batches and average.

        When ``self.structural_metrics`` is enabled, per-batch real/generated
        return tensors are accumulated along with ``window_start_indices``
        extracted from ``metadata['timestamp']``.  The phased estimator then
        groups windows by ``start_index % T`` rather than positional order,
        making the spectral diagnostics correct on any DataLoader ordering.

        Args:
            loader: DataLoader to iterate over.
            task: Task instance with ``prepare_data()`` and ``evaluate_samples()``.
            max_batches: Maximum number of batches to process.  ``None`` →
                process all batches.  Use ``max_batches=1`` for quick
                single-batch validation.
            viz_save_dir: Directory to save per-batch visualisations.  Passed
                through to ``task.evaluate_samples()``.
        """
        total_batches = len(loader) if max_batches is None else min(max_batches, len(loader))
        batch_limit_str = f" (first {total_batches})" if max_batches is not None else ""

        # Per-batch metric accumulator (same as DiffusionTrainer)
        task_metrics: Dict[str, float] = {}
        count = 0

        # Optional accumulators for structural / NLL diagnostics
        all_real_returns: List[torch.Tensor] = []
        all_gen_returns: List[torch.Tensor] = []
        # Pooled full ensemble for stylized-fact computation:
        # [B*n, T, N] per batch — every generated sample for every window.
        all_gen_returns_full: List[torch.Tensor] = []
        all_start_indices: List[torch.Tensor] = []
        all_nll_real: List[torch.Tensor] = []
        all_nll_gen: List[torch.Tensor] = []
        all_cum_nll_real: List[torch.Tensor] = []
        all_cum_nll_gen: List[torch.Tensor] = []

        print(f"\nGenerating GRW ensemble predictions on [{eval_split_name}]{batch_limit_str}...")
        for i, data in tqdm(enumerate(loader), desc=f"GRW [{eval_split_name}]", total=total_batches):
            data = data.to(self.device)

            # Ground truth via task (returns [B, T, N, F] in standardised space)
            data_dict = task.prepare_data(data)
            targets = data_dict["samples"]      # [B, T, N, F]
            metadata = data_dict["metadata"]

            B = targets.size(0)

            # ----------------------------------------------------------
            # Detect double-replication: if the loader's dataset is a
            # ReplicatedDataset the data is already duplicated n times.
            # GRW generates its *own* n samples via predict_ensemble(),
            # so feeding it pre-replicated data is a config error.
            #
            # NOTE: metadata['n_samples_per_input'] comes from the *task*
            # config (not the dataset), so it may be >1 even when the
            # dataset is un-replicated.  We only check on the first batch.
            # ----------------------------------------------------------
            if i == 0:
                from graph_signal_diffusion.datasets.replicated_dataset import ReplicatedDataset
                raw_dataset = getattr(loader, "dataset", None)
                if isinstance(raw_dataset, ReplicatedDataset):
                    raise RuntimeError(
                        "GRW detected a ReplicatedDataset in the loader.  "
                        "GRW handles its own multi-sample generation, so the "
                        "dataset must use n_samples_per_input=1 to avoid "
                        "double replication.  Set dataset.n_samples_per_input=1 "
                        "in your config or CLI override."
                    )

            # Ensemble predictions [B*n, T, N, F]
            predictions = self.predict_ensemble(data)

            # Replicate targets to [B*n, T, N, F] (same as ReplicatedDataset)
            targets_rep = targets.repeat_interleave(self.n_samples, dim=0)

            # Replicate tensor-valued metadata along dim 0
            meta_rep = self._replicate_metadata(metadata, self.n_samples)
            meta_rep["n_samples_per_input"] = self.n_samples
            meta_rep["batch_size"] = B * self.n_samples

            # Evaluate this batch immediately (no accumulation of tensors)
            batch_metrics = task.evaluate_samples(
                predictions, targets_rep, meta_rep, viz_save_dir=viz_save_dir
            )

            # ----------------------------------------------------------
            # Collect returns for structural / NLL diagnostics
            # ----------------------------------------------------------
            if self.structural_metrics or self.nll_metrics:
                # [B, T, N] — squeeze feature dim
                real_ret = targets.squeeze(-1).detach().cpu()
                # First sample per input only (1-to-1 with ground truth).
                # predictions is [B*n, T, N, 1] reshaped from [B, n, T, N, 1],
                # so element k = (batch k//n, sample k%n).  Stride by n_samples
                # to select sample-0 for every batch item.
                gen_ret = predictions[::self.n_samples].squeeze(-1).detach().cpu()

            if self.structural_metrics:
                all_real_returns.append(real_ret)
                all_gen_returns.append(gen_ret)
                # Full pooled ensemble for stylized-fact recompute.
                # predictions: [B*n, T, N, 1] → [B*n, T, N]
                all_gen_returns_full.append(
                    predictions.squeeze(-1).detach().cpu()
                )
                # Extract per-window start index from timestamp metadata
                ts = metadata.get("timestamp", None)
                if ts is not None:
                    N_nodes = real_ret.shape[2]  # number of stocks
                    # timestamp is [B*N]; take every N-th element
                    idx = ts[::N_nodes].detach().cpu().long()
                    all_start_indices.append(idx)

            if self.nll_metrics:
                all_nll_real.append(self.compute_nll(real_ret))
                all_nll_gen.append(self.compute_nll(gen_ret))
                all_cum_nll_real.append(self.compute_cumulative_nll(real_ret))
                all_cum_nll_gen.append(self.compute_cumulative_nll(gen_ret))

            # Accumulate scalar metrics (same pattern as DiffusionTrainer)
            for k, v in batch_metrics.items():
                if k not in task_metrics:
                    task_metrics[k] = 0.0
                task_metrics[k] += v
            count += 1

            if self.log_every_n_batches and (i + 1) % self.log_every_n_batches == 0:
                print(f"  Processed {i + 1}/{total_batches} batches")

            # Stop if we've reached the batch limit
            if max_batches is not None and (i + 1) >= max_batches:
                break

        # Average task metrics across batches
        metrics: Dict[str, float] = {}
        for k in task_metrics:
            metrics[k] = task_metrics[k] / max(count, 1)

        # ----------------------------------------------------------
        # Structural metrics (cross-stock & temporal diagnostics)
        # ----------------------------------------------------------
        if self.structural_metrics and all_real_returns:
            cat_real = torch.cat(all_real_returns, dim=0)
            cat_gen = torch.cat(all_gen_returns, dim=0)
            cat_indices = (
                torch.cat(all_start_indices, dim=0)
                if all_start_indices else None
            )
            T_steps = cat_real.shape[1]
            struct = self.compute_structural_metrics(
                cat_real, cat_gen,
                max_lag=self.structural_max_lag,
                n_eigenvalues=self.structural_n_eigenvalues,
                window_stride=T_steps,
                window_start_indices=cat_indices,
            )
            metrics.update(struct)

            # ----------------------------------------------------------
            # Recompute non-linear stylized facts (kurtosis / vol-clustering /
            # momentum / top-eigval) on the *full* concatenated tensors.
            # task.evaluate_samples() computes these per-batch and the loop
            # above averages the per-batch values, which is biased for
            # 4th-moment / ratio-style statistics.  Computing them once over
            # all accumulated returns gives the unbiased dataset-level value
            # and makes cross-baseline comparison meaningful.
            #
            # cat_real has one trajectory per window; cat_gen_full pools all
            # n_samples generated trajectories for each window for a much
            # lower-variance estimate of the model's distribution.
            try:
                from graph_signal_diffusion.tasks.stock_price_forecasting.evaluator import (
                    StockPriceForecastingTaskV2,
                )
                cat_gen_full = torch.cat(all_gen_returns_full, dim=0)
                metrics.update(
                    StockPriceForecastingTaskV2.compute_stylized_facts_from_tensors(
                        cat_real, cat_gen_full,
                    )
                )
            except Exception:
                import traceback
                print(
                    "[GRW] Failed to recompute stylized facts on full tensors; "
                    "keeping per-batch averages.\n" + traceback.format_exc()
                )

            # Expose tensors for cross-baseline comparative plots
            self.last_structural_tensors = {
                "real": cat_real,
                "gen": cat_gen,
                "window_start_indices": cat_indices,
                "window_stride": T_steps,
            }

            if viz_save_dir is not None:
                import os
                self._plot_structural_metrics(
                    cat_real, cat_gen,
                    save_path=os.path.join(viz_save_dir, "structural_metrics_grw.pdf"),
                    max_lag=self.structural_max_lag,
                    n_eigenvalues=self.structural_n_eigenvalues,
                    dpi=self.plot_dpi,
                    window_stride=T_steps,
                    window_start_indices=cat_indices,
                )
                self._plot_autocorr_per_stock(
                    cat_real, cat_gen,
                    save_path=os.path.join(viz_save_dir, "autocorr_per_stock_grw.pdf"),
                    max_lag=self.structural_max_lag,
                    dpi=self.plot_dpi,
                    window_stride=T_steps,
                    window_start_indices=cat_indices,
                )
                sm.plot_autocorr_violin(
                    cat_real, cat_gen,
                    save_path=os.path.join(viz_save_dir, "autocorr_violin_grw.pdf"),
                    max_lag=self.structural_max_lag,
                    dpi=self.plot_dpi,
                    model_name="GRW",
                    window_stride=T_steps,
                    window_start_indices=cat_indices,
                )
                sm.plot_autocorr_heatmap(
                    cat_gen,
                    save_path=os.path.join(viz_save_dir, "autocorr_heatmap_grw.pdf"),
                    max_lag=self.structural_max_lag,
                    dpi=self.plot_dpi,
                    model_name="GRW",
                    window_stride=T_steps,
                    window_start_indices=cat_indices,
                    real_returns=cat_real,
                )
                # Cumulative-return std vs horizon
                import numpy as np
                N_stocks = cat_real.shape[2]
                T_steps  = cat_real.shape[1]
                sigma_bar = float(np.mean(
                    [self.per_stock_stds.get(s, self.global_std)
                     for s in range(N_stocks)]
                ))
                theoretical = sigma_bar * np.sqrt(np.arange(1, T_steps + 1))
                _cum_std_real = self.compute_cumulative_return_std(cat_real).numpy()
                _cum_std_gen = self.compute_cumulative_return_std(cat_gen).numpy()
                _cum_std_real_tn = self.compute_cumulative_return_std(
                    cat_real, per_stock=True,
                ).numpy()
                _cum_std_gen_tn = self.compute_cumulative_return_std(
                    cat_gen, per_stock=True,
                ).numpy()
                self._plot_cumulative_return_std(
                    _cum_std_real, _cum_std_gen,
                    save_path=os.path.join(viz_save_dir, "cumulative_return_std_grw.pdf"),
                    theoretical=theoretical,
                    std_real_tn=_cum_std_real_tn,
                    std_gen_tn=_cum_std_gen_tn,
                    dpi=self.plot_dpi,
                )

                # Dump consolidated plot-data sidecar for replot_baselines.
                if self.dump_plot_data:
                    try:
                        from graph_signal_diffusion.evaluation.plot_data_io import (
                            dump_per_baseline_structural,
                        )
                        dump_per_baseline_structural(
                            os.path.join(viz_save_dir, "structural_data.npz"),
                            cat_real=cat_real,
                            cat_gen=cat_gen,
                            model_name="GRW",
                            max_lag=self.structural_max_lag,
                            n_eigenvalues=self.structural_n_eigenvalues,
                            window_stride=T_steps,
                            window_start_indices=cat_indices,
                            cum_std_real=_cum_std_real,
                            cum_std_gen=_cum_std_gen,
                            cum_std_real_tn=_cum_std_real_tn,
                            cum_std_gen_tn=_cum_std_gen_tn,
                            theoretical=theoretical,
                            dpi=self.plot_dpi,
                        )
                    except Exception:
                        import traceback
                        print(
                            "[GRW] Failed to dump structural plot data sidecar:\n"
                            + traceback.format_exc()
                        )

        # ----------------------------------------------------------
        # NLL metrics (per-trajectory NLL histograms + W1 distance)
        # ----------------------------------------------------------
        if self.nll_metrics and all_nll_real:
            nll_real = torch.cat(all_nll_real)
            nll_gen = torch.cat(all_nll_gen)
            metrics["nll_mean_real"] = nll_real.mean().item()
            metrics["nll_mean_gen"] = nll_gen.mean().item()
            metrics["nll_std_real"] = nll_real.std().item()
            metrics["nll_std_gen"] = nll_gen.std().item()
            nll_real_np = nll_real.numpy()
            nll_gen_np = nll_gen.numpy()
            metrics["nll_w1"] = float(
                wasserstein_distance(nll_real_np, nll_gen_np)
            )

            # Cumulative-return NLL tensors — always computed so that
            # cross-baseline consumers can read last_nll_tensors without
            # requiring a viz directory.
            cum_nll_real_bt = torch.cat(all_cum_nll_real).numpy()  # [B_total, T]
            cum_nll_gen_bt  = torch.cat(all_cum_nll_gen).numpy()

            # Expose for cross-baseline comparative NLL plots
            self.last_nll_tensors = {
                "nll_real": nll_real_np,
                "nll_gen": nll_gen_np,
                "cum_nll_real": cum_nll_real_bt,
                "cum_nll_gen": cum_nll_gen_bt,
            }

            if viz_save_dir is not None:
                import os
                self._plot_nll_histograms(
                    nll_real_np, nll_gen_np,
                    save_path=os.path.join(viz_save_dir, "nll_histogram_grw.pdf"),
                    bins=self.plot_bins,
                    dpi=self.plot_dpi,
                    log_x=self.plot_nll_log_x,
                )
                w1_per_t = self._plot_cumulative_nll_histograms(
                    cum_nll_real_bt, cum_nll_gen_bt,
                    save_path=os.path.join(viz_save_dir, "cumulative_nll_histogram_grw.pdf"),
                    bins=self.plot_bins,
                    dpi=self.plot_dpi,
                )

                if self.dump_plot_data:
                    try:
                        from graph_signal_diffusion.evaluation.plot_data_io import (
                            dump_per_baseline_nll,
                        )
                        dump_per_baseline_nll(
                            os.path.join(viz_save_dir, "nll_data.npz"),
                            nll_real=nll_real_np,
                            nll_gen=nll_gen_np,
                            cum_nll_real_bt=cum_nll_real_bt,
                            cum_nll_gen_bt=cum_nll_gen_bt,
                            bins=self.plot_bins,
                            dpi=self.plot_dpi,
                            log_x=self.plot_nll_log_x,
                            scoring_model_name="GRW",
                        )
                    except Exception:
                        import traceback
                        print(
                            "[GRW] Failed to dump NLL plot data sidecar:\n"
                            + traceback.format_exc()
                        )
                if w1_per_t is not None:
                    for ti, w in enumerate(w1_per_t):
                        metrics[f"cum_nll_w1_t{ti+1}"] = w

        print(
            f"\nGRW [{eval_split_name}]: evaluated {count} batches (averaged metrics over {count} batches)"
        )

        return metrics

    # ------------------------------------------------------------------
    # Metadata helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _replicate_metadata(
        metadata: Dict[str, Any], n: int
    ) -> Dict[str, Any]:
        """Replicate tensor-valued metadata entries ``n`` times along dim 0.

        Tensors that encode per-stock data in PyG-batched layout
        ``[B*N, ...]`` (such as ``close_price`` and ``close_price_y``)
        need batch-aware replication: reshape to ``[B, N, ...]``,
        replicate along dim 0 to ``[B*n, N, ...]``, then flatten back
        to ``[B*n*N, ...]``.  Naive ``repeat_interleave`` on the flat
        tensor would garble the stock ordering.
        """
        N = metadata.get('num_stocks', None)
        B = metadata.get('batch_size', None)
        # Keys that have [B*N, ...] layout in PyG-batched data
        per_stock_keys = {'close_price', 'close_price_y', 'stocks_index'}

        out: Dict[str, Any] = {}
        for key, val in metadata.items():
            if not isinstance(val, torch.Tensor) or val.dim() < 1:
                out[key] = val
                continue

            if key in per_stock_keys and N is not None and B is not None:
                total = val.shape[0]
                expected_flat = B * N
                if total == expected_flat:
                    # Reshape [B*N, ...] -> [B, N, ...], replicate along
                    # batch dim, then flatten back to [B*n*N, ...]
                    rest = val.shape[1:]  # remaining dims
                    val_bn = val.view(B, N, *rest)              # [B, N, ...]
                    val_bn = val_bn.repeat_interleave(n, dim=0)  # [B*n, N, ...]
                    out[key] = val_bn.reshape(B * n * N, *rest)  # [B*n*N, ...]
                    continue

            # Default: simple repeat_interleave on dim 0
            out[key] = val.repeat_interleave(n, dim=0)
        return out

    # ------------------------------------------------------------------
    # Inspection
    # ------------------------------------------------------------------

    def get_params(self) -> Dict[str, Any]:
        """Return summary of fitted parameters."""
        if self.global_mean is None:
            return {"status": "not_fitted"}

        return {
            "global_mean": self.global_mean,
            "global_std": self.global_std,
            "n_stocks": len(self.per_stock_means),
            "mean_min": min(self.per_stock_means.values()),
            "mean_max": max(self.per_stock_means.values()),
            "std_min": min(self.per_stock_stds.values()),
            "std_max": max(self.per_stock_stds.values()),
            "n_samples": self.n_samples,
            "shrinkage_strength": self.shrinkage_strength,
            "evaluation": {
                "structural_metrics": self.structural_metrics,
                "structural_max_lag": self.structural_max_lag,
                "structural_n_eigenvalues": self.structural_n_eigenvalues,
                "nll_metrics": self.nll_metrics,
                "log_every_n_batches": self.log_every_n_batches,
                "plot_bins": self.plot_bins,
                "plot_dpi": self.plot_dpi,
                "plot_nll_log_x": self.plot_nll_log_x,
            },
        }
    
    @staticmethod
    def display_comparison_metrics(
        csv_path: str,
        metrics: Optional[List[str]] = None,
        splits: Optional[List[str]] = None,
        decimals: int = 4,
        format: str = "grouped",
    ):
        """Display key metrics from baseline_comparison.csv in readable table format.
        
        This is a convenience method that wraps the evaluation utility function
        for extracting and displaying metrics from comparison results.
        
        Args:
            csv_path: Path to baseline_comparison.csv file.
            metrics: List of metric names to extract. 
                     Defaults to ['rmse', 'crps_mean', 'crps_std', 'mae', 'mse'].
            splits: List of data splits. Defaults to ['train-val', 'val', 'test'].
            decimals: Number of decimal places to display.
            format: Display format - "grouped" (by split) or "flat" (single table).
        
        Returns:
            DataFrame with the extracted metrics.
        
        Example:
            >>> GeometricRandomWalk.display_comparison_metrics(
            ...     'outputs/stock_price_forecasting_v2-sp500_cleaned/comparison/2026-02-16/14-15-25/baseline_comparison.csv'
            ... )
        """
        from graph_signal_diffusion.evaluation import display_metrics_table
        return display_metrics_table(csv_path, metrics=metrics, splits=splits, decimals=decimals, format=format)
    
    @staticmethod
    def save_comparison_metrics_markdown(
        csv_path: str,
        output_path: Optional[str] = None,
        metrics: Optional[List[str]] = None,
        splits: Optional[List[str]] = None,
        decimals: int = 4,
        format: str = "grouped",
    ):
        """Save formatted metrics table to a markdown file.
        
        This is a convenience method that wraps the evaluation utility function
        for saving comparison results as markdown.
        
        Args:
            csv_path: Path to baseline_comparison.csv file.
            output_path: Path to save the markdown file. If None, saves to the same
                        directory as csv_path with name 'metrics_summary.md'.
            metrics: List of metric names to extract. 
                     Defaults to ['rmse', 'crps_mean', 'crps_std', 'mae', 'mse'].
            splits: List of data splits. Defaults to ['train-val', 'val', 'test'].
            decimals: Number of decimal places to display.
            format: Display format - "grouped" (by split) or "flat" (single table).
        
        Example:
            >>> GeometricRandomWalk.save_comparison_metrics_markdown(
            ...     'outputs/stock_price_forecasting_v2-sp500_cleaned/comparison/2026-02-16/14-15-25/baseline_comparison.csv'
            ... )
        """
        from graph_signal_diffusion.evaluation import save_metrics_table_markdown
        from pathlib import Path
        
        if output_path is None:
            csv_dir = Path(csv_path).parent
            output_path = str(csv_dir / "metrics_summary.md")
        
        return save_metrics_table_markdown(
            csv_path, output_path,
            metrics=metrics, splits=splits,
            decimals=decimals, format=format
        )