import os
import numpy as np

# ---- geometry MUST match _ugnn_graph_macros.tex ----
N      = 8
gC     = (N-1)/2.0
gSp    = 0.40
half   = (N-1)/2.0*gSp
gDbase = 2.0
bumps  = [(-0.42*half, 0.40*half),
          ( 0.48*half, 0.06*half),
          (-0.06*half,-0.48*half)]

# ---- selection knobs ----
ALPHA = 0.50     # 0 = pure top-energy (clusters), 1 = pure uniform random
SEED  = 73       # fixes the uniform perturbation draw

# energy on the IDEAL (un-jittered) lattice -- selection is jitter-independent
energy = np.zeros((N,N))
for i in range(N):
    for j in range(N):
        lx=(i-gC)*gSp; ly=(j-gC)*gSp
        energy[i,j]=max(np.exp(-gDbase*np.hypot(lx-bx,ly-by)/half) for bx,by in bumps)
e = (energy-energy.min())/(energy.max()-energy.min())

rng = np.random.default_rng(SEED)
u   = rng.random((N,N))
key = (1-ALPHA)*e + ALPHA*u           # perturbed score (higher = selected earlier)

flat = sorted(((key[i,j], i, j) for i in range(N) for j in range(N)), reverse=True)
pri  = np.zeros((N,N), dtype=int)
for rank,(k,i,j) in enumerate(flat):
    pri[i,j]=rank                      # 0..63 ; active at depth iff pri < N_b

# ---- emit LaTeX lookup table ----
out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "_ugnn_graph_priority.tex")
with open(out,"w") as f:
    f.write("% _ugnn_graph_priority.tex  --  AUTO-GENERATED by gen_priority.py (do not hand-edit)\n")
    f.write("%% nested top-N selection priorities for the fixed 8x8 graph (Fig 1b insets).\n")
    f.write("%% active at depth b  <=>  pri < N_b, with N_b in {64,32,16,8}.\n")
    f.write("%% rule: key = (1-%.2f)*energy_norm + %.2f*uniform(seed=%d)  (energy-biased but spread).\n"
            % (ALPHA,ALPHA,SEED))
    for i in range(N):
        for j in range(N):
            f.write("\\expandafter\\def\\csname ugP@%d@%d\\endcsname{%d}\n"%(i,j,pri[i,j]))

def show(Nb,tag):
    print(f"--- depth set |.|={Nb} ({tag}) ---")
    for j in range(N-1,-1,-1):                 # print top row first
        print("".join("#" if pri[i,j]<Nb else "." for i in range(N)))
for Nb,tag in [(64,"d1"),(32,"d2"),(16,"d3"),(8,"d4")]:
    show(Nb,tag)
print("counts:", [int((pri<Nb).sum()) for Nb in (64,32,16,8)])
print("wrote", out)
