import os
import numpy as np

# ---- geometry MUST match _ugnn_graph_macros.tex (ideal lattice; jitter is negligible vs sigma) ----
N   = 8
gC  = (N-1)/2.0
gSp = 0.40
pos = np.array([[((i-gC)*gSp, (j-gC)*gSp) for j in range(N)] for i in range(N)])  # (N,N,2), cm

# ---- noise knobs ----
SEED      = 2027
AMP_BIG   = 0.60        # x_k corruption noise amplitude (zero-mean, range +-AMP/2)
AMP_SMALL = 0.18        # xhat_0 residual-error amplitude (independent, much smaller than x_k)
# SIGMA = spatial low-pass bandwidth per depth (grid units); level 1 = 0 -> pure per-node speckle.
SIGMA   = {1: 0.0, 2: 0.45, 3: 0.70, 4: 0.95}
# Per-depth RMS floors (variability that survives). Bumped up so depths 2-4 stay clearly varied.
ENC_RMS = {1: 0.190, 2: 0.160, 3: 0.140, 4: 0.120}   # encoder residual noise (added to clean)
EPS_RMS = {1: 0.185, 2: 0.160, 3: 0.140, 4: 0.120}   # decoder noise estimate eps = x_k - xhat (on grey)
HAT_RMS = 0.085                                        # xhat_0 clean-estimate residual (added to clean)

rng   = np.random.default_rng(SEED)
big   = AMP_BIG   * (rng.random((N, N, 3)) - 0.5)     # x_k corruption noise
small = AMP_SMALL * (rng.random((N, N, 3)) - 0.5)     # xhat_0 residual error (independent)

def lp(field, sig):
    if sig <= 1e-6:
        return field.copy()
    out = np.empty_like(field)
    for i in range(N):
        for j in range(N):
            d2 = (pos[:, :, 0] - pos[i, j, 0])**2 + (pos[:, :, 1] - pos[i, j, 1])**2
            w  = np.exp(-d2 / (2.0 * (sig*gSp)**2)); w /= w.sum()
            out[i, j] = (w[:, :, None] * field).sum(axis=(0, 1))
    return out

def renorm(field, target):
    cur = float(np.sqrt((field**2).mean()))
    return field * (target / cur if cur > 1e-9 else 1.0)

nz = {lvl: renorm(lp(big,         SIGMA[lvl]), ENC_RMS[lvl]) for lvl in SIGMA}  # encoder residual noise
ne = {lvl: renorm(lp(big - small, SIGMA[lvl]), EPS_RMS[lvl]) for lvl in SIGMA}  # decoder eps = x_k - xhat
nh = renorm(small, HAT_RMS)                                                      # xhat_0 small residual

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "_ugnn_graph_noise.tex")
lines = ["% _ugnn_graph_noise.tex  --  AUTO-GENERATED by gen_lpnoise.py (do not hand-edit)",
         "%% nz = encoder residual noise (LP of x_k corruption);  base = clean_smoothed (mode 1)",
         "%% ne = decoder noise estimate eps = x_k - xhat_0 (LP);  base = grey 0.5      (mode 3)",
         "%% nh = xhat_0 small residual error (full-res);          base = clean         (mode 2)",
         "%% all zero-mean, renormalised to per-depth RMS floors so variability survives.",
         "%% AMP_BIG=%.2f AMP_SMALL=%.2f SIGMA=%s ENC_RMS=%s EPS_RMS=%s HAT_RMS=%.3f SEED=%d"
         % (AMP_BIG, AMP_SMALL, SIGMA, ENC_RMS, EPS_RMS, HAT_RMS, SEED)]
for lvl in SIGMA:
    for i in range(N):
        for j in range(N):
            for ch, nm in zip(nz[lvl][i, j], "RGB"):
                lines.append("\\expandafter\\def\\csname nz%s@%d@%d@%d\\endcsname{%.4f}" % (nm, lvl, i, j, ch))
            for ch, nm in zip(ne[lvl][i, j], "RGB"):
                lines.append("\\expandafter\\def\\csname ne%s@%d@%d@%d\\endcsname{%.4f}" % (nm, lvl, i, j, ch))
for i in range(N):
    for j in range(N):
        for ch, nm in zip(nh[i, j], "RGB"):
            lines.append("\\expandafter\\def\\csname nh%s@%d@%d\\endcsname{%.4f}" % (nm, i, j, ch))

with open(out, "w") as f:
    f.write("\n".join(lines) + "\n")
print("nz RMS:", {k: round(float(np.sqrt((v**2).mean())), 4) for k, v in nz.items()})
print("ne RMS:", {k: round(float(np.sqrt((v**2).mean())), 4) for k, v in ne.items()})
print("nh RMS:", round(float(np.sqrt((nh**2).mean())), 4))
print("wrote", out)
